# Generated by Django 2.0.1 on 2018-06-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('room_size', models.IntegerField()),
                ('nightly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guests', models.IntegerField()),
                ('breakfast_included', models.BooleanField()),
                ('view', models.CharField(max_length=50)),
            ],
        ),
    ]
